### ISSUE TITLE
Ariane 5

### ISSUE THREAD

**Issue by mdennehy** [danluu/post-mortems#22]
http://www.around.com/ariane.html

http://erps-list.erps.narkive.com/IIbZDa62/ariane-post-mortem

A seven billion dollar error caused by legacy code from Ariane 4 that wasn't even needed on Ariane 5 but which was left in place to reduce the risk of introducing problems, combined with never actually testing the flight software with the expected trajectory of the new rocket.

**Comment by Trismegiste** [comment]
more details on https://en.wikipedia.org/wiki/Cluster_%28spacecraft%29?oldid=217305667

>Because of the different flight path, a data conversion from a 64-bit floating point to 16-bit signed integer value caused a hardware exception (more specifically, an arithmetic overflow, as the floating point number had a value too large to be represented by a 16-bit signed integer)
